/*
 * generated by Xtext 2.16.0
 */
package org.ezyaml.lang.tosca.tests

import com.google.inject.Inject
import java.io.IOException
import java.io.OutputStream
import java.io.PrintStream
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.util.stream.Collectors
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.^extension.ExtendWith
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource
import org.ezyaml.lang.tosca.yaml.YamlDocument
import org.junit.jupiter.api.DisplayName
import static org.junit.jupiter.api.Assertions.*
import java.util.List

@ExtendWith(InjectionExtension)
@InjectWith(YamlInjectorProvider)
@DisplayName("Parse All YAMLs")
class BulkYamlParserTest {
	@Inject
	ParseHelper<YamlDocument> parseHelper

	static	String[] configFilePaths = #["./test-resources/devops/descriptor-packages"];
	
		val dummy = new PrintStream(new OutputStream() {
			override write(int b) throws IOException {
				// DO NOTHING
			}
		})
		val original = System.out

	def static Path[] getFiles() {
		val List<Path> paths = newArrayList()
		configFilePaths.forEach[configFilePath|paths.addAll((Files.walk(Paths.get(configFilePath)).collect(Collectors.toList())))]
		paths.filter[p|Files.isRegularFile(p) && p.toString.endsWith(".yaml")]
	// toMap([toString], [parseHelper.parse((new org.eclipse.xtend.lib.macro.file.Path(toString)).contents)])
	}

	@ParameterizedTest(name="{0}")
	@MethodSource("getFiles")
	def void parseYaml(Path p) {
		try {
			System.setOut(dummy)
			var r = parseHelper.parse(new String(Files.readAllBytes(p)))
			System.setOut(original)
			Assertions.assertNotNull(r)
			var errors = r.eResource.errors
			Assertions.assertTrue(errors.isEmpty, '''Errors while parsing «p.toString»: «errors.join("\n\t")»''')
		} catch (Throwable t) {
			System.setOut(original)
			fail('''Error while parsing «p.toString»: «t.message»''',t)
			
		}

	}
}
/*
 *  #this is the single line comment
 * type is bad:  Specifies IPv6 address mode
 * c is sad: 
 *  [
 *   [a is a bad alphabet,  bb is too bad alphabet, but C is actually good ]
 *  ]
 */
