/*
 * generated by Xtext 2.18.0
 */
package org.ezyaml.lang.tosca.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.ezyaml.lang.tosca.yaml.YamlDocument
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(YamlInjectorProvider)
class ToscaImportTest {
	@Inject
	ParseHelper<YamlDocument> parseHelper
	
	@Test
	def void load() {
		val result = parseHelper.parse('''
		imports:
		- data.yaml
		- file: data.yaml		
		  repository: data-repo		
		  namespace_uri: http://www.w3.org/1999/xhtml	
		  namespace_prefix: tosca.uncommon
		imports:
		 - pp.yaml
		imports:
		  - some_definition_file: path1/path2/some_defs.yaml
		  - another_definition_file:
		      file: path1/path2/file2.yaml
		      repository: my_service_catalog
		      namespace_uri: http://mycompany.com/tosca/1.0/platform
		      namespace_prefix: mycompany
 
''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
