/*
 * generated by Xtext 2.16.0
 */
package org.ezyaml.lang.tosca.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.ezyaml.lang.tosca.yaml.YamlDocument

@ExtendWith(InjectionExtension)
@InjectWith(YamlInjectorProvider)
class YamlParsingTest {
	@Inject
	ParseHelper<YamlDocument> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse(
'''definitions:
  CreatePmJobRequest:
    description: >
      This type represents a request to create a PM job. 
      It shall comply with the provisions defined in Table 7.5.2.6-1.
    type: object
    required:
      - objectInstanceIds
      - criteria 
    properties:
      objectInstanceIds:
        description: >
          Identifiers of the NS instances for which
          performance information is requested to be collected.
        type: "array"
        items:   
          $ref: "SOL005_def.yaml#/definitions/Identifier"
      criteria:
        description: >
          Criteria of the collection of performance information.
        $ref: "#/definitions/PmJobCriteria"
        
  PmJobCriteria:
    description: >
      This type represents collection criteria for PM jobs. 
      It shall comply with the provisions defined in Table 7.5.3.3-1.
    type: object
    required:
      - collectionPeriod
      - reportingPeriod 
    properties:
      performanceMetric:
        description: >
          This defines the types of performance metrics
          for the specified object instances. At least one
          of the two attributes (performance metric or
          group) shall be present.
        type: "array"
        items:   
          $ref: "SOL005_def.yaml#/definitions/String"
      performanceMetricGroup:
        description: >
          Group of performance metrics.
          A metric group is a pre-defined list of metrics,
          known to the producer that it can decompose to
          individual metrics. At least one of the two
          attributes (performance metric or group) shall
          be present.
        type: "array"
        items:   
          $ref: "SOL005_def.yaml#/definitions/String"          
      collectionPeriod:
        description: >
          Specifies the periodicity at which the producer
          will collect performance information. The unit
          shall be seconds.
          At the end of each reportingPeriod, the producer will inform the consumer about availability of the performance
          data collected for each completed collection period during this reportingPeriod. The reportingPeriod should be
          equal to or a multiple of the collectionPeriod. In the latter case, the performance data for the collection periods
          within one reporting period are reported together.    
          In particular when choosing short collection and reporting periods, the number of PM jobs that can be
          supported depends on the capability of the producing entity.
        type: integer
        minimum: 0
        default: 0       
      reportingPeriod:
        description: >
          Specifies the periodicity at which the producer
          will report to the consumer.
          about performance information. The unit shall be seconds.
          At the end of each reportingPeriod, the producer will inform the consumer about availability of the performance
          data collected for each completed collection period during this reportingPeriod. The reportingPeriod should be
          equal to or a multiple of the collectionPeriod. In the latter case, the performance data for the collection periods
          within one reporting period are reported together.    
          In particular when choosing short collection and reporting periods, the number of PM jobs that can be
          supported depends on the capability of the producing entity.          
        type: integer
        minimum: 0
        default: 0        
      reportingBoundary:
        description: >
          Identifies a time boundary after which the
          reporting will stop. The boundary shall allow a
          single reporting as well as periodic reporting up
          to the boundary.
        $ref: "SOL005_def.yaml#/definitions/DateTime"

  PmJob:
    description: >
      This type represents a PM job.
    type: object
    required:
      - id
      - objectInstanceIds
      - criteria     
    properties:
      id:
        description: >
          Identifier of this PM job.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      objectInstanceIds:
        description: >
          Identifiers of the NS instances for which
          performance information is collected.
        type: array
        items:
          $ref: "SOL005_def.yaml#/definitions/Identifier"
      criteria:
        description: >
          Criteria of the collection of performance information.
        $ref: "#/definitions/PmJobCriteria"
      reports:
        description: >
          Information about available reports collected by this PM job.
        type: object
        required:
          - href
          - readyTime
          - _links
        properties:
          href:
            description: >
              The Uri where the report can be obtained.
            $ref: "SOL005_def.yaml#/definitions/Uri"
          readyTime:
            description: >
              The time when the report was made available.
            $ref: "SOL005_def.yaml#/definitions/DateTime"
          expiryTime:
            description: >
              The time when the report will expire.
            $ref: "SOL005_def.yaml#/definitions/DateTime"
          fileSize:
            description: >
              The size of the report file in bytes, if known.
            type: integer            
          _links:
            description: >
              Links for this resource.
            type: object
            required:
              - self
            properties:
              self:
                description: >
                  URI of this resource.
                $ref: "SOL005_def.yaml#/definitions/Link"
              objects:
                description: >
                  Links to resources representing the NS
                  instances for which performance information is
                  collected. Shall be present if the NS instance
                  information is accessible as a resource.
                type: array
                items: 
                  $ref: "SOL005_def.yaml#/definitions/Link"
                  
  CreateThresholdRequest:
    description: >
      This type represents a request to create a threshold.
    type: object
    required:
      - objectInstanceId
      - criteria
    properties: 
      objectInstanceId:
        description: >
          Identifier of the NS instance associated with this threshold.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      criteria:
        description: >
          Criteria that define this threshold.
        $ref: "#/definitions/ThresholdCriteria"
        
  Threshold:
    description: >
      This type represents a threshold.
    type: object
    required: 
      - id
      - objectInstanceId
      - criteria
      - _links
    properties: 
      id:
        description: >
          Identifier of this threshold resource.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      objectInstanceId:
        description: >
          Identifier of the NS instance associated with the threshold.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      criteria:
        description: >
          Criteria that define this threshold.
        $ref: "#/definitions/ThresholdCriteria"
      _links:
        description: >
          Links for this resource.
        type: object
        required: 
          - self
        properties: 
          self:
            description: >
              URI of this resource.
            $ref: "SOL005_def.yaml#/definitions/Link"
          object: 
            description: >
              Link to a resource representing the NS instance for
              which performance information is collected. Shall be
              present if the NS instance information is accessible as
              a resource.
              
  ThresholdCriteria:
    description: >
      This type represents criteria that define a threshold.
    type: object
    required: 
      - performanceMetric
      - thresholdType
    properties: 
      performanceMetric:
        description: >
          Defines the performance metric associated with the
          threshold, as specified in ETSI GS NFV-IFA 027).
        type: string
      thresholdType:
        description: >
          Type of threshold. This attribute determines which other attributes
          are present in the data structure.
          Permitted values:
          * SIMPLE: Single-valued static threshold
          In the present document, simple thresholds are defined. The
          definition of additional threshold types is left for future
          specification.
        type: string
        enum:
          - SIMPLE
      simpleThresholdDetails:
        description: >
          Details of a simple threshold. Shall be present if
          thresholdType="SIMPLE".
        type: object
        required: 
          - thresholdValue
          - hysteresis
        properties: 
          thresholdValue:
            description: >
              The threshold value. Shall be represented as a floating point
              number.               
            type: integer
          hysteresis:
            description: >
              The hysteresis of the threshold. Shall be represented as a
              non-negative floating point number.
              A notification with crossing direction "UP" will be generated if
              the measured value reaches or exceeds
              "thresholdValue" + "hysteresis". A notification with crossing
              direction "DOWN" will be generated if the measured value reaches
              or undercuts "thresholdValue" - "hysteresis".
              The hysteresis is defined to prevent storms of threshold
              crossing notifications. When processing a request to create a
              threshold, implementations should enforce a suitable minimum
              value for this attribute (e.g. override the value or reject the
              request).
            type: integer
            
  PmSubscriptionRequest:
    description: >
      This type represents a subscription request.
    type: object
    required: 
      - callbackUri
    properties:
      filter:
        description: >
          Filter settings for this subscription, to define the subset of
          all notifications this subscription relates to. A particular
          notification is sent to the subscriber if the filter matches,
          or if there is no filter.
        $ref: "#/definitions/PmNotificationsFilter"
      callbackUri:
        description: >
          The URI of the endpoint to send the notification to.
        $ref: "SOL005_def.yaml#/definitions/Uri"
      authentication:
        description: >
          Authentication parameters to conFigure the use of
          Authorization when sending notifications corresponding
          to this subscription, as defined in clause 4.5.3.4.
          This attribute shall only be present if the subscriber
          requires authorization of notifications..
        $ref: "SOL005_def.yaml#/definitions/SubscriptionAuthentication"
        
  PmNotificationsFilter:
    description: >
      This type represents a filter that can be used to subscribe for 
      notifications related to performance management events. It
      shall comply with the provisions defined in Table 7.5.3.2-1.
      At a particular nesting level in the filter structure, the following applies: 
      All attributes shall match in order for the filter
      to match (logical "and" between different filter attributes). 
      If an attribute is an array, the attribute shall match if at least
      one of the values in the array matches (logical "or" between the values of one filter attribute).
    type: object
    properties: 
      nsInstanceSubscriptionFilter:
        description: >
          Filter criteria to select NS instances about which to notify.
        $ref: "SOL005_def.yaml#/definitions/NSInstanceSubscriptionFilter"
      notificationTypes:
        description: >
          Match particular notification types.
          Permitted values:
          - ThresholdCrossedNotification
          - PerformanceInformationAvailableNotification
          The permitted values of the "notificationTypes" attribute are
          spelled exactly as the names of the notification types to facilitate
          automated code generation systems.          
        type: array
        items:
          type: string
          enum:
            - ThresholdCrossedNotification
            - PerformanceInformationAvailableNotification
  PmSubscription:
    description: >
      This type represents a subscription.
    type: object
    required: 
      - id
      - callbackUri
      - _links
    properties: 
      id:
        description: >
          Identifier that identifies the subscription.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      filter:
        description: >
          Filter settings for this subscription, to define the subset of all
          notifications this subscription relates to. A particular
          notification is sent to the subscriber if the filter matches, or if
          there is no filter.
        $ref: "#/definitions/PmNotificationsFilter"
      callbackUri:
        description: >
          The URI of the endpoint to send the notification to.
        $ref: "SOL005_def.yaml#/definitions/Uri"
      _links:
        description: >
          Links to resources related to this resource.
        type: object
        required:
          - self
        properties:
          self:
            description: >
              URI of this resource.
            $ref: "SOL005_def.yaml#/definitions/Link"
            
  Version:
    description: >
      Software version of the VNF. This is
      changed when there is any change to the
      software included in the VNF package.
      This information is copied from the VNFD.
      It shall be present after the VNF package
      content has been on-boarded and absent otherwise.
    type: string

  Checksum:
    description: >
      This type represents the checksum of a VNF package or an artifact file.  
    required:
      - algorithm
      - hash
    type: object
    properties:
      algorithm:
        description: >
          Name of the algorithm used to generate the checksum,
          as defined in ETSI GS NFV-SOL 004 [5]. For example, SHA-256, SHA-512.
        type: string
      hash:
        description: >
          The hexadecimal value of the checksum.
        type: string
  Link:
    type: "object"
    
  PerformanceInformationAvailableNotification:
    description: >
      This notification informs the receiver that performance information is available.
    type: object
    required:
      - id
      - notificationType
      - subscriptionId
      - timeStamp
      - objectInstanceId
      - _links
    properties:
      id:
        description: >
          Identifier of this notification. If a notification is
          sent multiple times due to multiple
          subscriptions, the "id" attribute of all these
          notifications shall have the same value.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      notificationType:
        description: >
          Discriminator for the different notification types.
          Shall be set to
          "PerformanceInformationAvailableNotification"
          for this notification type.
        type: string
      subscriptionId:
        description: >
          Identifier of the subscription that this notification relates to.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      timeStamp:
        description: >
          Date and time of the generation of the notification.
        $ref: "SOL005_def.yaml#/definitions/DateTime"
      objectInstanceId:
        description: >
          Identifier that identifies a NS instance.
        $ref: "SOL005_def.yaml#/definitions/Identifier"        
      _links:
        description: >
          Links to resources related to this notification.
        type: object
        required:
          - subscription
          - pmJob
          - performanceReport
        properties:
          subscription:
            description: >
              Link to the related subscription.
            $ref: "SOL005_def.yaml#/definitions/Link"
          objectInstance:
            description: >
              Link to the resource representing the NS
              instance to which the notified change applies.
              Shall be present if the NS instance information
              is accessible as a resource.
            $ref: "SOL005_def.yaml#/definitions/Link"
          pmJob:
            description: >
              Link to the resource that represents the PM job
              for which performance information is available.
            $ref: "SOL005_def.yaml#/definitions/Link"
          performanceReport:
            description: >
              Link from which the available performance
              information of data type "PerformanceReport"
              (see clause 7.5.2.10) can be obtained.
              This link should point to an "Individual
              performance report" resource as defined in
              clause 6.4.3a.
            $ref: "SOL005_def.yaml#/definitions/Link"

  ThresholdCrossedNotification:
    description: >
      This type represents a notification that is sent when a threshold has been crossed.
    type: object
    required:
      - id
      - notificationType
      - subscriptionId
      - timeStamp
      - thresholdId
      - crossingDirection
      - objectInstanceId
      - performanceMetric
      - performanceValue
      - _links
    properties:
      id:
        description: >
          Identifier of this notification. If a notification is
          sent multiple times due to multiple
          subscriptions, the "id" attribute of all these
          notifications shall have the same value..
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      notificationType:
        description: >
          Discriminator for the different notification types.
          Shall be set to "ThresholdCrossedNotification "
          for this notification type.
        type: string
      subscriptionId:
        description: >
          Identifier of the subscription that this notification relates to.
        $ref: "SOL005_def.yaml#/definitions/Identifier"
      timeStamp:
        description: >
          Date and time of the generation of the notification.
        $ref: "SOL005_def.yaml#/definitions/DateTime"
      thresholdId:
        description: >
          Identifier of the threshold which has been crossed.
        $ref: "SOL005_def.yaml#/definitions/Identifier"    
      crossingDirection:
        description: >
          An indication of whether the threshold was crossed in upward or downward direction.
        $ref: "#/definitions/CrossingDirectionType"    
      objectInstanceId:
        description: >
          Identifier that identifies a NS instance.
        $ref: "SOL005_def.yaml#/definitions/Identifier"            
      performanceMetric:
        description: >
          Performance metric associated with the threshold.
        type: string
      performanceValue:
        description: >
          Value of the metric that resulted in threshold crossing. See note.
        type: object        
      _links:
        description: >
          Links to resources related to this notification.
        type: object
        required:
          - subscription
          - objectInstance
          - threshold
        properties:
          subscription:
            description: >
              Link to the related subscription.
            $ref: "SOL005_def.yaml#/definitions/Link"
          objectInstance:
            description: >
              Link to the resource representing the NS
              instance to which the notified change applies.
              Shall be present if the NS instance information
              is accessible as a resource..
            $ref: "SOL005_def.yaml#/definitions/Link"
          threshold:
            description: >
              Link to the resource that represents the
              threshold that was crossed.
            $ref: "SOL005_def.yaml#/definitions/Link"            
            
  CrossingDirectionType:
    description: >
      The enumeration CrossingDirectionType shall comply with the provisions.  
      Acceptable Values are:
      UP - The threshold was crossed in upward direction.
      DOWN - The threshold was crossed in downward direction.
    type: string
    enum:
      - UP
      - DOWN
''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
/*
 #this is the single line comment
type is bad:  Specifies IPv6 address mode
c is sad: 
 [
  [a is a bad alphabet,  bb is too bad alphabet, but C is actually good ]
 ]
 
 
#this is the single line comment
long string: this is a very long string
  and this is its second part
  but there is a third part also
type is bad:  [ a, b, c ]
this type is worse: { a is good but not better: [x, y, z], b: false, c is for cat: third place gets a bronze }



 
 */