/*
 * generated by Xtext 2.18.0
 */
package org.ezyaml.lang.tosca


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class YamlStandaloneSetup extends YamlStandaloneSetupGenerated {

	def static void doSetup() {
		new YamlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
